use_frameworks!

platform :ios, '8.0'

target 'TRUNetworking_Example' do
  pod 'TRUNetworking', :path => '../'

  target 'TRUNetworking_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
